version: '3.7'
services:
  python:
    env_file: .compose_env
    build: .
    ports:
      - "5000:5000"
    container_name: "python-redis-test"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
    command: "python redis_test.py"
    
  redis:
    env_file: .compose_env
    image: "redis:alpine"
    command: >
      --port ${REDIS_PORT}